// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lloppzhbjenttkaabwaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsb3BwemhiamVudHRrYWFid2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTY0MDIsImV4cCI6MjA1OTEzMjQwMn0.VzNpU0H27o--yWYerW-uf28YxJ4sGD9YLJkc7Pc-FLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);